before_install:
- openssl aes-256-cbc -K $encrypted_3c652d0d846c_key -iv $encrypted_3c652d0d846c_iv
  -in deploy_key.enc -out deploy_key -d
script:
- qmake RevisionToDateConverter.pro -r -spec linux-g++
- make
deploy:
  provider: releases
  file: ./build/release/RevisionToDateConverter 
  skip_cleanup: true
  on:
    repo: mtompkins/revision-to-date-converter
