######################################################################
# Automatically generated by qmake (3.0) Wed May 4 08:16:39 2016
######################################################################

TEMPLATE = app
TARGET = revisiontodateconverter
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h time_delta.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp time_delta.cpp
RESOURCES += resources.qrc
